---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# gemini

The `gemini` package allows users to analyze combinatorial CRISPR screens as described in Zamanighomi et al. ?.

## Installation
To install the latest development version of `gemini`, use the [`devtools`]("https://github.com/r-lib/devtools") package as follows:
```{r, eval = F}
devtools::install_github(repo = "sellerslab/gemini", build_vignettes = TRUE)
```

You can (eventually) install the stable release version of gemini from [Bioconductor](https://www.bioconductor.org/) with:

```{r, eval = F}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("gemini")
```

## Details
See the vignette for usage instructions:
```{r}
vignette("gemini-quickstart", package = "gemini")
```

